name: MOT
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  dio: ^3.0.10
  intl: "^0.16.1"
  charts_flutter: ^0.9.0
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.7
  sembast: ^2.4.0
  sentry: ^3.0.1
  flutter_bloc: ^3.2.0
  flutter_spinkit: "^4.1.2"
  font_awesome_flutter: ^8.8.1
  google_nav_bar: ^2.2.0
  url_launcher: ^5.4.2
  flutter_offline: ^0.3.0
  data_connection_checker: ^0.3.4
  cloud_firestore: any
  firebase_auth: any
  firebase_core: any
  firebase_messaging: any
  firebase_storage: 4.0.0
  firebase_analytics: ^6.3.0
  multi_image_picker: any
  flutter_absolute_path: ^1.0.6
  provider: ^4.3.3
  rxdart: any
  syncfusion_flutter_charts: ^18.4.41
  flutter_svg: ^0.19.3
  syncfusion_flutter_datagrid: any
  collection: any
  #plaid_flutter: ^1.1.6
  equatable: any
  mvc_pattern: ^3.4.1
  image_picker: any
  photo_view: ^0.10.2
  video_trimmer: ^0.3.2
  video_thumbnail: ^0.2.4
  cached_network_image: any
  shared_preferences: any
  flutter_rating_bar: any
  rating_dialog: any
  rect_getter: 0.0.1




dev_dependencies:
  flutter_launcher_icons: ^0.7.4

  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: "launcher_icon" 
  image_path: "assets/icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/stock.json
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
